name: 'Wait for commit statuses'
description: 'Wait for commit statuses to be either successful or failed'
branding:
  icon: 'clock'
  color: 'orange'
inputs:
  payload:
    description: 'Object containing the options'
    required: true
outputs:
  status:
    description: 'Success or failure'
runs:
  using: 'docker'
  image: 'Dockerfile'
